name: Run CodeforcesRanking CLI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Use 'adopt' distribution on Windows
          architecture: x64

      - name: Compile Project
        run: |
          javac -d bin -cp ".\CodeforcesRanking\dist\lib\*" -Xlint:deprecation .\CodeforcesRanking\src\codeforcesranking\*.java

      - name: Run CLI
        run: |
          java -cp ".\bin;.\CodeforcesRanking\dist\lib\*;.\CodeforcesRanking\dist\lib\*" codeforcesranking.Main cmrit25 21r01 22r05a Manohar_Eldhandi Vishwatej4 yash_37 Sadanand26

      - name: Archive Generated File
        run: |
          mkdir -p ${{ github.workspace }}\LeaderboardsStorage
          move .\CodeforcesRanking\Leaderboards\CurrentCodeforcesRatings.xlsx ${{ github.workspace }}\LeaderboardsStorage

      - name: Remote Time
        # You may pin to the exact commit or the version.
        # uses: Plabick/Remote-Time-Action@3621a863d43a89838f2469fc31c679c6f695a132
        uses: Plabick/Remote-Time-Action@1.01
        with:
        # The [timezone code](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) to recieve the current time in. Defaults to utc (+0)
          timezone: 'IST' # optional, default is utc

      - name: Commit Generated CSV File
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ github.workspace }}\Leaderboards\CurrentCodeforcesRatings.csv
          git commit -m "Add generated leaderboard data - ${{steps.time.outputs.epochTime}}"
          git push


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Leaderboard
          path: ${{ github.workspace }}\Leaderboards
